//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spelletje.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spelletje.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|!|Hello Stranger, what is your name?|1: Hello, my name is test.&gt;1.1&lt;2: Bye&gt;1.2#
        ///1.1|!|Nice meeting you test, i currently am a bit busy.|4: Exit&gt;close#
        ///1.2|!|Goodbye|4: Exit&gt;close#.
        /// </summary>
        internal static string Bart {
            get {
                return ResourceManager.GetString("Bart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|!|Mainframe is booting, please stand by.|1: ENTER&gt;1,1#
        ///1.1|!|.................\n3.. 2.. 1..|1: ENTER&gt;1.2#
        ///1.2|!|Welcome User.\nNetwork Connection: Dissconnected!|1: Reconnect&gt;1.3&lt;2: Local protocol&gt;2.1&lt;3: Restart mainframe&gt;1.4#
        ///1.3|!|Retrying connection, please stand by.|1: ENTER&gt;1.2#
        ///1.4|!|Restarting mainframe, please stand by.|1: ENTER&gt;1#
        ///
        ///2.1|!|List of protocols:\nRepopulation\nSystem test\nMainframe overwrite|1: Repopulation&gt;3.1&lt;2: System Test&gt;2.2&lt;3: Mainframe overwrite&gt;2.3#
        ///2.2|!|System test cu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Prologue {
            get {
                return ResourceManager.GetString("Prologue", resourceCulture);
            }
        }
    }
}
